require("dotenv").config({ path: "../.env" });
const mongoose = require("mongoose");
const Mentor = require("../models/Mentor");

const mentors = [
  {
    name: "Rahul Sharma",
    phone: "9876543210",
    whatsapp: "9876543210",
    village: "Piparia",
    district: "Hoshangabad",
    state: "Madhya Pradesh",
    currentStatus: "Working",
    currentOrganization: "Infosys, Pune",
    field: "Software Engineering",
    stream: "Science",
    highestEducation: "B.E. Computer Science",
    canMentorIn: [
      "College Admission",
      "Engineering Entrance",
      "Career Guidance",
      "IT Jobs",
    ],
    languagesSpoken: ["Hindi", "English"],
    availableDays: ["Saturday", "Sunday"],
    availableTime: "6 PM - 9 PM",
    bio: "From Piparia village, now working as a software engineer. Happy to guide students from my village.",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Priya Verma",
    phone: "9823456789",
    whatsapp: "9823456789",
    village: "Rampur",
    district: "Hoshangabad",
    state: "Madhya Pradesh",
    currentStatus: "Working",
    currentOrganization: "Government Hospital, Hoshangabad",
    field: "Medical",
    stream: "Science",
    highestEducation: "MBBS",
    canMentorIn: [
      "NEET Preparation",
      "Medical Admission",
      "Scholarship Guidance",
      "Career in Medicine",
    ],
    languagesSpoken: ["Hindi"],
    availableDays: ["Sunday"],
    availableTime: "10 AM - 12 PM",
    bio: "First doctor from my village. I know how tough it is — happy to help students aiming for medical.",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Suresh Patel",
    phone: "9812345678",
    whatsapp: "9812345678",
    village: "Keshopur",
    district: "Bhopal",
    state: "Madhya Pradesh",
    currentStatus: "Self-Employed",
    currentOrganization: "SP Electronics (own shop)",
    field: "Electronics & Repair",
    stream: "Science",
    highestEducation: "ITI — Electrician",
    canMentorIn: [
      "ITI Admission",
      "Starting own business",
      "Electronics Trade",
      "Skill Development",
    ],
    languagesSpoken: ["Hindi"],
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    availableTime: "7 PM - 9 PM",
    bio: "Started with ITI, now run my own electronics shop. ITI is a great option if you want quick employment.",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Anita Dubey",
    phone: "9834567890",
    whatsapp: "9834567890",
    village: "Sehore Town",
    district: "Sehore",
    state: "Madhya Pradesh",
    currentStatus: "Working",
    currentOrganization: "State Bank of India, Sehore",
    field: "Banking & Finance",
    stream: "Commerce",
    highestEducation: "B.Com + MBA",
    canMentorIn: [
      "Bank Exam Preparation",
      "Commerce Stream Guidance",
      "MBA Admission",
      "Government Jobs",
    ],
    languagesSpoken: ["Hindi", "English"],
    availableDays: ["Saturday", "Sunday"],
    availableTime: "4 PM - 7 PM",
    bio: "Working in SBI. Cleared IBPS after 2 attempts. Can guide students for bank and government exams.",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Mohan Lal Yadav",
    phone: "9845678901",
    whatsapp: "9845678901",
    village: "Piparia",
    district: "Hoshangabad",
    state: "Madhya Pradesh",
    currentStatus: "College Student",
    currentOrganization: "Barkatullah University, Bhopal",
    field: "Arts & Social Work",
    stream: "Arts",
    highestEducation: "M.A. Social Work (pursuing)",
    canMentorIn: [
      "Arts Stream Career",
      "NGO Work",
      "Social Work",
      "College Admission",
      "Scholarship Guidance",
    ],
    languagesSpoken: ["Hindi"],
    availableDays: ["Saturday", "Sunday", "Wednesday"],
    availableTime: "5 PM - 8 PM",
    bio: "Arts student from Piparia, now in Bhopal for MA. Can help students who want to pursue arts or social work.",
    isVerified: false,
    isActive: true,
  },
  {
    name: "Kavita Singh",
    phone: "9856789012",
    whatsapp: "9856789012",
    village: "Ujjain Village",
    district: "Ujjain",
    state: "Madhya Pradesh",
    currentStatus: "Working",
    currentOrganization: "Govt Primary School, Ujjain",
    field: "Teaching",
    stream: "Arts",
    highestEducation: "B.Ed",
    canMentorIn: [
      "Teaching Career",
      "B.Ed Admission",
      "Government Teacher Exam",
      "Girl Student Guidance",
    ],
    languagesSpoken: ["Hindi"],
    availableDays: ["Saturday", "Sunday"],
    availableTime: "3 PM - 6 PM",
    bio: "Government teacher from a village background. Specially passionate about mentoring girl students.",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Deepak Rawat",
    phone: "9867890123",
    whatsapp: "9867890123",
    village: "Indore Village",
    district: "Indore",
    state: "Madhya Pradesh",
    currentStatus: "Working",
    currentOrganization: "Reliance Retail, Indore",
    field: "Retail & Sales",
    stream: "Commerce",
    highestEducation: "12th + Diploma in Retail Management",
    canMentorIn: [
      "Retail Career",
      "Sales Jobs",
      "After 12th Commerce Options",
      "Diploma Courses",
    ],
    languagesSpoken: ["Hindi"],
    availableDays: ["Monday", "Tuesday"],
    availableTime: "8 PM - 10 PM",
    bio: "Working in retail after 12th commerce. You don't need a degree for a good job — skill matters more.",
    isVerified: true,
    isActive: true,
  },
];

const seedMentors = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected");
    await Mentor.deleteMany({});
    console.log("🗑️ Existing mentors cleared");
    const inserted = await Mentor.insertMany(mentors);
    console.log(`✅ ${inserted.length} mentors seeded successfully`);
    mongoose.connection.close();
    console.log("🔌 Connection closed");
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seedMentors();