require("dotenv").config({ path: "../.env" });
const mongoose = require("mongoose");
const Scholarship = require("../models/Scholarship");

const scholarships = [
  {
    name: "National Scholarship Portal — Post Matric",
    provider: "Ministry of Education, Govt of India",
    type: "Central Government",
    amount: 10000,
    amountDescription: "Up to ₹10,000 per year",
    eligibility: {
      categories: ["SC", "ST", "OBC", "EWS"],
      minMarks: 50,
      maxFamilyIncome: 250000,
      streams: ["Science", "Commerce", "Arts"],
      classes: ["11th", "12th", "B.A. 1st Year", "B.A. 2nd Year", "B.A. 3rd Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-10-31"),
    applicationLink: "https://scholarships.gov.in",
    description: "Post-matric scholarship for SC/ST/OBC/EWS students studying in class 11th and above.",
    documentsRequired: [
      "Caste Certificate",
      "Income Certificate",
      "Marksheet of previous class",
      "Bank Account Details",
      "Aadhaar Card",
    ],
    isActive: true,
  },
  {
    name: "Central Sector Scholarship for College Students",
    provider: "Ministry of Education, Govt of India",
    type: "Central Government",
    amount: 12000,
    amountDescription: "₹10,000/year for 1st-3rd year, ₹20,000/year for professional courses",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 80,
      maxFamilyIncome: 800000,
      streams: ["Science", "Commerce", "Arts"],
      classes: ["B.A. 1st Year", "B.A. 2nd Year", "B.A. 3rd Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-11-15"),
    applicationLink: "https://scholarships.gov.in",
    description: "For students who scored in top 20 percentile in class 12 board exams.",
    documentsRequired: [
      "Class 12 Marksheet",
      "Income Certificate",
      "Bank Account Details",
      "Aadhaar Card",
      "College Admission Letter",
    ],
    isActive: true,
  },
  {
    name: "MP Mukhyamantri Medhavi Vidyarthi Yojana",
    provider: "Madhya Pradesh Government",
    type: "State Government",
    amount: 150000,
    amountDescription: "Full tuition fee waiver for MP students",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 70,
      maxFamilyIncome: 600000,
      streams: ["Science", "Commerce", "Arts", "Engineering"],
      classes: ["B.A. 1st Year", "B.E. 1st Year"],
      gender: "Any",
      states: ["Madhya Pradesh"],
    },
    deadline: new Date("2024-09-30"),
    applicationLink: "http://scholarshipportal.mp.nic.in",
    description: "Full fee waiver for meritorious MP students in government and private colleges.",
    documentsRequired: [
      "Class 12 Marksheet",
      "MP Domicile Certificate",
      "Income Certificate",
      "Aadhaar Card",
      "College Fee Receipt",
    ],
    isActive: true,
  },
  {
    name: "Begum Hazrat Mahal National Scholarship",
    provider: "Maulana Azad Education Foundation",
    type: "Central Government",
    amount: 10000,
    amountDescription: "₹5,000 for class 9-10, ₹6,000 for class 11-12",
    eligibility: {
      categories: ["OBC", "SC", "ST", "EWS"],
      minMarks: 50,
      maxFamilyIncome: 200000,
      streams: ["Science", "Commerce", "Arts"],
      classes: ["9th", "10th", "11th", "12th"],
      gender: "Female",
      states: [],
    },
    deadline: new Date("2024-10-15"),
    applicationLink: "https://scholarships.gov.in",
    description: "Scholarship exclusively for meritorious girl students from minority communities.",
    documentsRequired: [
      "Minority Community Certificate",
      "Income Certificate",
      "Marksheet",
      "Bank Account Details",
      "Aadhaar Card",
    ],
    isActive: true,
  },
  {
    name: "Pre-Matric Scholarship for SC Students",
    provider: "Ministry of Social Justice, Govt of India",
    type: "Central Government",
    amount: 3500,
    amountDescription: "₹2,500 for day scholars, ₹3,500 for hostellers",
    eligibility: {
      categories: ["SC"],
      minMarks: 0,
      maxFamilyIncome: 250000,
      streams: ["Science", "Commerce", "Arts", "Not Applicable"],
      classes: ["9th", "10th"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-09-15"),
    applicationLink: "https://scholarships.gov.in",
    description: "For SC students studying in class 9th and 10th to prevent dropout.",
    documentsRequired: [
      "SC Caste Certificate",
      "Income Certificate",
      "Previous Class Marksheet",
      "Bank Account Details",
      "Aadhaar Card",
    ],
    isActive: true,
  },
  {
    name: "Post Matric Scholarship for ST Students",
    provider: "Ministry of Tribal Affairs, Govt of India",
    type: "Central Government",
    amount: 12000,
    amountDescription: "Maintenance allowance + tuition fees",
    eligibility: {
      categories: ["ST"],
      minMarks: 0,
      maxFamilyIncome: 250000,
      streams: ["Science", "Commerce", "Arts"],
      classes: ["11th", "12th", "B.A. 1st Year", "B.A. 2nd Year", "B.A. 3rd Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-11-30"),
    applicationLink: "https://scholarships.gov.in",
    description: "For ST students pursuing post-matric education. Covers tuition + maintenance.",
    documentsRequired: [
      "ST Certificate",
      "Income Certificate",
      "Marksheet",
      "Bank Account Details",
      "Aadhaar Card",
      "Domicile Certificate",
    ],
    isActive: true,
  },
  {
    name: "Inspire Scholarship for Higher Education",
    provider: "Department of Science & Technology",
    type: "Central Government",
    amount: 80000,
    amountDescription: "₹80,000 per year for 5 years",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 85,
      maxFamilyIncome: 0,
      streams: ["Science"],
      classes: ["B.Sc 1st Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-10-01"),
    applicationLink: "http://www.online-inspire.gov.in",
    description: "For top students pursuing B.Sc to encourage science research in India.",
    documentsRequired: [
      "Class 12 Marksheet (85%+)",
      "Science stream proof",
      "Bank Account Details",
      "Aadhaar Card",
    ],
    isActive: true,
  },
  {
    name: "Tata Trust Education Scholarship",
    provider: "Tata Trusts",
    type: "Private",
    amount: 50000,
    amountDescription: "Up to ₹50,000 per year",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 60,
      maxFamilyIncome: 400000,
      streams: ["Science", "Commerce", "Arts", "Engineering"],
      classes: ["B.A. 1st Year", "B.E. 1st Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-08-31"),
    applicationLink: "https://www.tatatrusts.org",
    description: "For first-generation college students from low-income families.",
    documentsRequired: [
      "Income Certificate",
      "Marksheet",
      "First-generation learner declaration",
      "Bank Account Details",
    ],
    isActive: true,
  },
  {
    name: "MP Gaon Ki Beti Yojana",
    provider: "Madhya Pradesh Government",
    type: "State Government",
    amount: 5000,
    amountDescription: "₹500/month for 10 months",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 60,
      maxFamilyIncome: 0,
      streams: ["Science", "Commerce", "Arts"],
      classes: ["B.A. 1st Year", "B.A. 2nd Year", "B.A. 3rd Year"],
      gender: "Female",
      states: ["Madhya Pradesh"],
    },
    deadline: new Date("2024-09-30"),
    applicationLink: "http://scholarshipportal.mp.nic.in",
    description: "For girls from rural areas of MP who scored 60%+ in class 12.",
    documentsRequired: [
      "Class 12 Marksheet (60%+)",
      "MP Domicile Certificate",
      "Rural Area Certificate",
      "Bank Account Details",
      "Aadhaar Card",
    ],
    isActive: true,
  },
  {
    name: "Aditya Birla Scholarship",
    provider: "Aditya Birla Group",
    type: "Private",
    amount: 65000,
    amountDescription: "₹65,000 per year",
    eligibility: {
      categories: ["General", "OBC", "SC", "ST", "EWS"],
      minMarks: 75,
      maxFamilyIncome: 600000,
      streams: ["Science", "Commerce", "Engineering"],
      classes: ["B.E. 1st Year", "MBA 1st Year"],
      gender: "Any",
      states: [],
    },
    deadline: new Date("2024-09-15"),
    applicationLink: "https://adityabirlascholars.net",
    description: "Merit-cum-means scholarship for students in premier engineering and management institutes.",
    documentsRequired: [
      "Marksheet",
      "Income Certificate",
      "College Admission Proof",
      "Bank Account Details",
    ],
    isActive: true,
  },
];

const seedScholarships = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected");

    await Scholarship.deleteMany({});
    console.log("🗑️ Existing scholarships cleared");

    const inserted = await Scholarship.insertMany(scholarships);
    console.log(`✅ ${inserted.length} scholarships seeded successfully`);

    mongoose.connection.close();
    console.log("🔌 Connection closed");
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seedScholarships();